package com.comp231.team6.models;

public enum Program {
	SOFTWARE_ENGINEERING_TECHNOLOGY,
	SOFTWARE_ENGINEERING_TECHNOLOGY_AI,
	GAME_PROGRAMMING,
	HEALTH_INFORMATICS_TECHNOLOGY,
	COMPUTER_SYSTEMS_TECHNOLOGY
}
